version: "3.9"


services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=chat_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=ae09db8ee173f11ea136f2665de6d398502162c7"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: